"""Application pipeline bounded context: candidacies, stages and their history."""

from opportunity_radar.pipeline.domain import (
    ALLOWED_TRANSITIONS,
    START_STAGES,
    TERMINAL_STAGES,
    ApplicationNotFoundError,
    ApplicationStage,
    ApplicationStatus,
    ApplicationVersionConflictError,
    DuplicateActiveApplicationError,
    InvalidStageTransitionError,
    InvalidStartStageError,
    NextAction,
    PipelineError,
    can_transition,
    is_terminal,
    status_for,
    validate_start,
    validate_transition,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "START_STAGES",
    "TERMINAL_STAGES",
    "ApplicationNotFoundError",
    "ApplicationStage",
    "ApplicationStatus",
    "ApplicationVersionConflictError",
    "DuplicateActiveApplicationError",
    "InvalidStageTransitionError",
    "InvalidStartStageError",
    "NextAction",
    "PipelineError",
    "can_transition",
    "is_terminal",
    "status_for",
    "validate_start",
    "validate_transition",
]
